ARM: Fix build after memfd_create syscall
Error: __NR_syscalls is not equal to the size of the syscall table

 Conflicts:
	arch/arm/include/asm/unistd.h
	arch/arm/include/uapi/asm/unistd.h